### ISSUE TITLE
Create PR & Issue Templates

### ISSUE THREAD

**Issue by Ivendrakeo** [Senior-Design-0x07/the-hobby-hub#15]
## Overview
All of the initial issues I created were done without too much form or style. However, going forward I see value in standardizing our communication so that we don't have to spend as much time analyzing the issue or PR.  Github has a built in feature for Issue & PR (Pull Request) templates but I am not sure exactly how to set them up.

## Goals
- Either create or find a good PR & Issue template that is applicable to our project's scope.
- Setup our repo/project to source those templates.

**Comment by rockboynton** [comment]
PR and issue templates completed!
