### ISSUE TITLE
Setup Beaglebone for development

### ISSUE THREAD

**Issue by Ivendrakeo** [Senior-Design-0x07/the-hobby-hub#16]

**Comment by Ivendrakeo** [comment]
Here are the steps to setup the board using the included debian image: 

1. Install an SSH client (preferably). I think you can use powershell or cmd but a client is much more convienent and provides better text wrapping, layout, etc. I personally like PuTTY (top download link): https://www.putty.org/

2. connect to the beaglebone wifi network. it should be an open network something like: `Beaglebone6074`

3. You should be able to then SSH into the beaglebone with the static IP: 192.168.7.2 *Port 22*. The default username is `root` with no password. You may also get a web ui popup when you connect to the beaglebone that has you connect to a network that way, but since I had networking problems I did all my networking on the physical device rather than the web UI. You can try and connect that way but i'm not sure if it will hard code your wi-fi network to auto-connect every time (which im sure you want to do for your home network).

4. If you want to follow the exact steps I did, instead of using the web ui, in my ssh session I followed the steps at this link under "connecting to a protected access point": https://wiki.archlinux.org/index.php/ConnMan#Connecting_to_a_protected_access_point

5. afterward, run `$ifconfig` and note the inet addr under wlan0. this is the default address you should now use to ssh into the beaglebone instead of the static ip we used earlier. while using the wlan0 ip, we can ssh into the beaglebone using any remote device on the network, so you can use a different computer or whatnot. 

Note: If your using PuTTY, remember you can "save" sessions so that you don't have to type in the IP every time! also use `$exit` in the putty prompt if you want to close the ssh session.

**Comment by iliescua** [comment]
I did it with the Web UI and that seemed to work! :)

**Comment by Ivendrakeo** [comment]
Here are the steps to install and update the debian image on the beaglebone. Currently this setup is going to be booting off the SD card. Further updates will be given to flash the EMMC after I've verified our process isn't going to brick the board, since that would be bad...

1.  Generally we'll be following the instructions here under the "Update to latest software" section. https://wiki.seeedstudio.com/BeagleBone_Green/#update-to-latest-software . Follow setups up to and including STEP 4!
**IMPORTANT:** When setting up microSD card, make sure you generate a MD5 Hash **BEFORE** writing to SD card.

2.  After you've flashed your sd card, hold the "USER" button and plug the Beaglebone in. you should see all four blue lights go solid, after which you can release the "USER" button. If you don't see ALL FOUR blue lights, then it's likely you either did something wrong or the sd reader pins are not touching the sd card as they should (this is the issue i've had). 

3. you'll end up having to wait ~3minutes for the board to boot up (it's very slow...) but eventually you'll see the WLAN &BT lights turn on, and shortly after you'll be able to ssh into the device. for SSH, you might want to try the static IP first `192.168.7.2` since it doesn't look like the wireless settings carry over from the EMMC boot.

**Comment by Ivendrakeo** [comment]
Here are the steps to flash the EMMC. It's pretty straightforward. 

1. You'll want to boot into the 2020 image from the previous step. Use usename: `debian` password: `temppwd`

2. Then follow step 5 under update-to-latest-software to change the u-boot settings to flash the emmc https://wiki.seeedstudio.com/BeagleBone_Green/#update-to-latest-software . Basically you'll want to uncomment the flashing line in uEnv.txt.
** Also `sudo apt-get install`   `dosfstools` and `rsync`.
![image](https://user-images.githubusercontent.com/58989670/100915342-d568fc00-3499-11eb-8e7c-a5d19f2fd536.png)


3.  Hold the user button and boot plug the beaglebone in to boot from the sd card. It should stutter a bit then have a scrolling blue light pattern to show the flashing process. When the lights are scrolling, you can release the user button. When all the lights turn off that means its done and you can unplug.

4. remove the sd card and plug the beaglebone back in. Connect Via Putty and ensure the board boots using the new 2020 image!

Congratulations setup is complete.

please comment on this thread once you've completed all these steps so we can tell when everyone is done : )

**Comment by rockboynton** [comment]
> Here are the steps to setup the board using the included debian image:
> 
> 1. Install an SSH client (preferably). I think you can use powershell or cmd but a client is much more convienent and provides better text wrapping, layout, etc. I personally like PuTTY (top download link): https://www.putty.org/
> 2. connect to the beaglebone wifi network. it should be an open network something like: `Beaglebone6074`
> 3. You should be able to then SSH into the beaglebone with the static IP: 192.168.7.2 _Port 22_. The default username is `root` with no password. You may also get a web ui popup when you connect to the beaglebone that has you connect to a network that way, but since I had networking problems I did all my networking on the physical device rather than the web UI. You can try and connect that way but i'm not sure if it will hard code your wi-fi network to auto-connect every time (which im sure you want to do for your home network).
> 4. If you want to follow the exact steps I did, instead of using the web ui, in my ssh session I followed the steps at this link under "connecting to a protected access point": https://wiki.archlinux.org/index.php/ConnMan#Connecting_to_a_protected_access_point
> 5. afterward, run `$ifconfig` and note the inet addr under wlan0. this is the default address you should now use to ssh into the beaglebone instead of the static ip we used earlier. while using the wlan0 ip, we can ssh into the beaglebone using any remote device on the network, so you can use a different computer or whatnot.
> 
> Note: If your using PuTTY, remember you can "save" sessions so that you don't have to type in the IP every time! also use `$exit` in the putty prompt if you want to close the ssh session.

Some comments:
* I used OpenSSH via Windows Terminal
* My apartment WiFi is one of those that is technically "open" but it redirects you to login with account and password, so I couldn't use the web interface. Usually these sorts of networks have a way to add devices that don't have a mechanism to sign in like on phones and PCs, and mine did indeed, however I forgot which IP address took me to the website to add the device. 
1. I had to run `ipconfig` to find the Wireless LAN adapter Wi-Fi: IPv4 address which took me there. Once there I needed the MAC address of the BeagleBone to add. To do that I connected to the BeagleBone WiFi and SSHed using the static IP 192.168.7.2 as root `ssh root@192.168.7.2` and then ran `ifconfig` and found the `wlan0` `HW addr` aka the MAC. 

2. After I added that went back on my apartment network, added the MAC, then ran `connmanctl scan wifi` and `connmanctl services` to find my network's "ID" then ran ` connmanctl connect <ID>`. 

3. After that I ran `ifconfig` again to get the `wlan0` `inet addr` which is what was used to subsequently ssh after completing the above. 

> Note: You can also just ssh using `ssh root@beaglebone`. You can even change "beaglebone" to be whatever you want using `hostnamectl set-hostname <funky_new_name>`

**Comment by rockboynton** [comment]
Done

**Comment by DeclanBruce** [comment]
Done

**Comment by rockboynton** [comment]
Everyone is all set up!
