### ISSUE TITLE
Host webserver over wlan0

### ISSUE THREAD

**Issue by Ivendrakeo** [Senior-Design-0x07/the-hobby-hub#26]
# Overview

if we are connected via wifi we want the web UI to be hosted over wlan0 instead of usb0. we expect the end user to have to setup the wifi once over USB but afterwards, we don't want them to have to constantly have a PC plugged into the board in order to access the web ui. Instead we want any device on the local network to be able to connect to the board.
# Goals

- we will first default to host the web server over usb but once the wifi is connected, we want the server to be hosted over wlan0 instead.

# Helpful Info

- you might need some sort of internal flag that checks to see if your connected to the wifi and if not then run over usb. 

# Verification Criteria

- if the board is not connected to wifi, then the server will be hosted over usb
- if the board is connected to wifi, we can access the web ui over wlan0. (test this by trying to access the web ui from a remote device on the local network)
# Task Advisor

@anthony-bartman 
@iliescua

**Comment by anthony-bartman** [comment]
https://flask.palletsprojects.com/en/1.1.x/deploying/#deployment 
This could be bad for using FLASK.... xD whoops. Might need to choose an app server like 'nginx', or lighttpd. Gotta do more research to see what all this stuff is...

**Comment by anthony-bartman** [comment]
@iliescua  This is the same thing as what I described in the other issue with the Wifi and Connectivity pages.
