### ISSUE TITLE
Investigate OpenWRT

### ISSUE THREAD

**Issue by Ivendrakeo** [Senior-Design-0x07/the-hobby-hub#3]
## Overview
From our understanding so far OpenWrt is possibly a complete (end-to-end) embedded Linux development solution. In order to get a better idea of what it's capable of we need to do an investigation to see what it can do and if we can utilize it as an embedded Linux development tool on our hobby hub. Also, look into BuildRoot for the same possibilities. 

We want to get this done before we delve too deep into an off the shelf solution.

## Results
- Is it only used for router software? If so, It may not have any value for our project.
- Is it a embedded Linux development tool for creating custom Linux images? 
    * If it is, how easy is it to use? Is there a large learning curve? 
    * How expandable is it? Do we have complete customization?
- Any other potentially useful information

**Comment by Ivendrakeo** [comment]
In addition to buildroot, another option is Yocto. @rockboynton sent a good link that gives some startup advice when building yocto with beaglebone in mind. you don't necessary need to fully investigate yocto (since im already very familiar with it) however i just wanted somewhere logical to keep track of that link rock sent ; ) https://jumpnowtek.com/beaglebone/BeagleBone-Systems-with-Yocto.html

**Comment by rockboynton** [comment]
Closing this as we decided not to go with OpenWRT.
