### ISSUE TITLE
Interface to allow user to interact with the program manager

### ISSUE THREAD

**Issue by Ivendrakeo** [Senior-Design-0x07/the-hobby-hub#42]
# Overview

Create an interface to allow the user to interact with the program manager

# Goals

add programs, remove programs, debug programs, pause & continue. etc.

# Helpful Info

# Verification Criteria

utility should work as the dev user.

# Task Advisor

@Ivendrakeo

**Comment by rockboynton** [comment]
@Ivendrakeo Can this be closed?
