### ISSUE TITLE
Return Boolean from pin manager commands

### ISSUE THREAD

**Issue by anthony-bartman** [Senior-Design-0x07/the-hobby-hub#47]
# Overview

I need a way to update the user whether or not my backend requests worked with your pin-manager commands; primarily the request pin method. As of now, there is no way for me to use your `-r pin_name` command and tell if the command was successful or it failed. Only the logs tell me that which I do not know how to store or view in a python variable.  The boolean will help me update user on the front end as to whether or not their pin-name was mapped as well.
# Goals
Simply return a boolean whether true or false for your commands to help me tell whether the command was sucessful for not.

# Helpful Info
None

# Verification Criteria
Reach out to me, should be simple enough @anthony-bartman 

# Task Advisor
@anthony-bartman

**Comment by rockboynton** [comment]
@anthony-bartman So I checked it out, and you should be able to check the result of `request_pin` and if it is NOT an empty string, then you got a valid pin. 
Or I could throw an exception that you can try/catch on the backend. There currently is an exception thrown if the pin is requested is already being used
