### ISSUE TITLE
Create Test "user programs"

### ISSUE THREAD

**Issue by Ivendrakeo** [Senior-Design-0x07/the-hobby-hub#9]
- programs we can use to simulate user defined programs and test our software with.

##TODO

**Comment by iliescua** [comment]
Configured VSCode as a remote host to the Putty SSH client. For details on how to do this follow the guide outlined at this url: https://www.digitalocean.com/community/tutorials/how-to-use-visual-studio-code-for-remote-development-via-the-remote-ssh-plugin
